// Full periodic table dataset: 118 elements with real names, atomic mass, and category
// category drives the color-coding on the table (standard chemistry convention)
const PERIODIC_ELEMENTS = [
  { symbol: "H", name: "Hydrogen", number: 1, mass: "1.008", row: 1, col: 1, category: "nonmetal" },
  { symbol: "He", name: "Helium", number: 2, mass: "4.003", row: 1, col: 18, category: "noble-gas" },

  { symbol: "Li", name: "Lithium", number: 3, mass: "6.94", row: 2, col: 1, category: "alkali-metal" },
  { symbol: "Be", name: "Beryllium", number: 4, mass: "9.012", row: 2, col: 2, category: "alkaline-earth" },
  { symbol: "B", name: "Boron", number: 5, mass: "10.81", row: 2, col: 13, category: "metalloid" },
  { symbol: "C", name: "Carbon", number: 6, mass: "12.011", row: 2, col: 14, category: "nonmetal" },
  { symbol: "N", name: "Nitrogen", number: 7, mass: "14.007", row: 2, col: 15, category: "nonmetal" },
  { symbol: "O", name: "Oxygen", number: 8, mass: "15.999", row: 2, col: 16, category: "nonmetal" },
  { symbol: "F", name: "Fluorine", number: 9, mass: "18.998", row: 2, col: 17, category: "halogen" },
  { symbol: "Ne", name: "Neon", number: 10, mass: "20.180", row: 2, col: 18, category: "noble-gas" },

  { symbol: "Na", name: "Sodium", number: 11, mass: "22.990", row: 3, col: 1, category: "alkali-metal" },
  { symbol: "Mg", name: "Magnesium", number: 12, mass: "24.305", row: 3, col: 2, category: "alkaline-earth" },
  { symbol: "Al", name: "Aluminium", number: 13, mass: "26.982", row: 3, col: 13, category: "post-transition" },
  { symbol: "Si", name: "Silicon", number: 14, mass: "28.085", row: 3, col: 14, category: "metalloid" },
  { symbol: "P", name: "Phosphorus", number: 15, mass: "30.974", row: 3, col: 15, category: "nonmetal" },
  { symbol: "S", name: "Sulfur", number: 16, mass: "32.06", row: 3, col: 16, category: "nonmetal" },
  { symbol: "Cl", name: "Chlorine", number: 17, mass: "35.45", row: 3, col: 17, category: "halogen" },
  { symbol: "Ar", name: "Argon", number: 18, mass: "39.948", row: 3, col: 18, category: "noble-gas" },

  { symbol: "K", name: "Potassium", number: 19, mass: "39.098", row: 4, col: 1, category: "alkali-metal" },
  { symbol: "Ca", name: "Calcium", number: 20, mass: "40.078", row: 4, col: 2, category: "alkaline-earth" },
  { symbol: "Sc", name: "Scandium", number: 21, mass: "44.956", row: 4, col: 3, category: "transition-metal" },
  { symbol: "Ti", name: "Titanium", number: 22, mass: "47.867", row: 4, col: 4, category: "transition-metal" },
  { symbol: "V", name: "Vanadium", number: 23, mass: "50.942", row: 4, col: 5, category: "transition-metal" },
  { symbol: "Cr", name: "Chromium", number: 24, mass: "51.996", row: 4, col: 6, category: "transition-metal" },
  { symbol: "Mn", name: "Manganese", number: 25, mass: "54.938", row: 4, col: 7, category: "transition-metal" },
  { symbol: "Fe", name: "Iron", number: 26, mass: "55.845", row: 4, col: 8, category: "transition-metal" },
  { symbol: "Co", name: "Cobalt", number: 27, mass: "58.933", row: 4, col: 9, category: "transition-metal" },
  { symbol: "Ni", name: "Nickel", number: 28, mass: "58.693", row: 4, col: 10, category: "transition-metal" },
  { symbol: "Cu", name: "Copper", number: 29, mass: "63.546", row: 4, col: 11, category: "transition-metal" },
  { symbol: "Zn", name: "Zinc", number: 30, mass: "65.38", row: 4, col: 12, category: "transition-metal" },
  { symbol: "Ga", name: "Gallium", number: 31, mass: "69.723", row: 4, col: 13, category: "post-transition" },
  { symbol: "Ge", name: "Germanium", number: 32, mass: "72.630", row: 4, col: 14, category: "metalloid" },
  { symbol: "As", name: "Arsenic", number: 33, mass: "74.922", row: 4, col: 15, category: "metalloid" },
  { symbol: "Se", name: "Selenium", number: 34, mass: "78.971", row: 4, col: 16, category: "nonmetal" },
  { symbol: "Br", name: "Bromine", number: 35, mass: "79.904", row: 4, col: 17, category: "halogen" },
  { symbol: "Kr", name: "Krypton", number: 36, mass: "83.798", row: 4, col: 18, category: "noble-gas" },

  { symbol: "Rb", name: "Rubidium", number: 37, mass: "85.468", row: 5, col: 1, category: "alkali-metal" },
  { symbol: "Sr", name: "Strontium", number: 38, mass: "87.62", row: 5, col: 2, category: "alkaline-earth" },
  { symbol: "Y", name: "Yttrium", number: 39, mass: "88.906", row: 5, col: 3, category: "transition-metal" },
  { symbol: "Zr", name: "Zirconium", number: 40, mass: "91.224", row: 5, col: 4, category: "transition-metal" },
  { symbol: "Nb", name: "Niobium", number: 41, mass: "92.906", row: 5, col: 5, category: "transition-metal" },
  { symbol: "Mo", name: "Molybdenum", number: 42, mass: "95.95", row: 5, col: 6, category: "transition-metal" },
  { symbol: "Tc", name: "Technetium", number: 43, mass: "[98]", row: 5, col: 7, category: "transition-metal" },
  { symbol: "Ru", name: "Ruthenium", number: 44, mass: "101.07", row: 5, col: 8, category: "transition-metal" },
  { symbol: "Rh", name: "Rhodium", number: 45, mass: "102.906", row: 5, col: 9, category: "transition-metal" },
  { symbol: "Pd", name: "Palladium", number: 46, mass: "106.42", row: 5, col: 10, category: "transition-metal" },
  { symbol: "Ag", name: "Silver", number: 47, mass: "107.868", row: 5, col: 11, category: "transition-metal" },
  { symbol: "Cd", name: "Cadmium", number: 48, mass: "112.414", row: 5, col: 12, category: "transition-metal" },
  { symbol: "In", name: "Indium", number: 49, mass: "114.818", row: 5, col: 13, category: "post-transition" },
  { symbol: "Sn", name: "Tin", number: 50, mass: "118.710", row: 5, col: 14, category: "post-transition" },
  { symbol: "Sb", name: "Antimony", number: 51, mass: "121.760", row: 5, col: 15, category: "metalloid" },
  { symbol: "Te", name: "Tellurium", number: 52, mass: "127.60", row: 5, col: 16, category: "metalloid" },
  { symbol: "I", name: "Iodine", number: 53, mass: "126.904", row: 5, col: 17, category: "halogen" },
  { symbol: "Xe", name: "Xenon", number: 54, mass: "131.293", row: 5, col: 18, category: "noble-gas" },

  { symbol: "Cs", name: "Caesium", number: 55, mass: "132.905", row: 6, col: 1, category: "alkali-metal" },
  { symbol: "Ba", name: "Barium", number: 56, mass: "137.327", row: 6, col: 2, category: "alkaline-earth" },
  { symbol: "La", name: "Lanthanum", number: 57, mass: "138.905", row: 6, col: 3, category: "lanthanide" },
  { symbol: "Hf", name: "Hafnium", number: 72, mass: "178.49", row: 6, col: 4, category: "transition-metal" },
  { symbol: "Ta", name: "Tantalum", number: 73, mass: "180.948", row: 6, col: 5, category: "transition-metal" },
  { symbol: "W", name: "Tungsten", number: 74, mass: "183.84", row: 6, col: 6, category: "transition-metal" },
  { symbol: "Re", name: "Rhenium", number: 75, mass: "186.207", row: 6, col: 7, category: "transition-metal" },
  { symbol: "Os", name: "Osmium", number: 76, mass: "190.23", row: 6, col: 8, category: "transition-metal" },
  { symbol: "Ir", name: "Iridium", number: 77, mass: "192.217", row: 6, col: 9, category: "transition-metal" },
  { symbol: "Pt", name: "Platinum", number: 78, mass: "195.085", row: 6, col: 10, category: "transition-metal" },
  { symbol: "Au", name: "Gold", number: 79, mass: "196.967", row: 6, col: 11, category: "transition-metal" },
  { symbol: "Hg", name: "Mercury", number: 80, mass: "200.592", row: 6, col: 12, category: "transition-metal" },
  { symbol: "Tl", name: "Thallium", number: 81, mass: "204.38", row: 6, col: 13, category: "post-transition" },
  { symbol: "Pb", name: "Lead", number: 82, mass: "207.2", row: 6, col: 14, category: "post-transition" },
  { symbol: "Bi", name: "Bismuth", number: 83, mass: "208.980", row: 6, col: 15, category: "post-transition" },
  { symbol: "Po", name: "Polonium", number: 84, mass: "[209]", row: 6, col: 16, category: "metalloid" },
  { symbol: "At", name: "Astatine", number: 85, mass: "[210]", row: 6, col: 17, category: "halogen" },
  { symbol: "Rn", name: "Radon", number: 86, mass: "[222]", row: 6, col: 18, category: "noble-gas" },

  { symbol: "Fr", name: "Francium", number: 87, mass: "[223]", row: 7, col: 1, category: "alkali-metal" },
  { symbol: "Ra", name: "Radium", number: 88, mass: "[226]", row: 7, col: 2, category: "alkaline-earth" },
  { symbol: "Ac", name: "Actinium", number: 89, mass: "[227]", row: 7, col: 3, category: "actinide" },
  { symbol: "Rf", name: "Rutherfordium", number: 104, mass: "[267]", row: 7, col: 4, category: "transition-metal" },
  { symbol: "Db", name: "Dubnium", number: 105, mass: "[268]", row: 7, col: 5, category: "transition-metal" },
  { symbol: "Sg", name: "Seaborgium", number: 106, mass: "[269]", row: 7, col: 6, category: "transition-metal" },
  { symbol: "Bh", name: "Bohrium", number: 107, mass: "[270]", row: 7, col: 7, category: "transition-metal" },
  { symbol: "Hs", name: "Hassium", number: 108, mass: "[269]", row: 7, col: 8, category: "transition-metal" },
  { symbol: "Mt", name: "Meitnerium", number: 109, mass: "[278]", row: 7, col: 9, category: "unknown" },
  { symbol: "Ds", name: "Darmstadtium", number: 110, mass: "[281]", row: 7, col: 10, category: "unknown" },
  { symbol: "Rg", name: "Roentgenium", number: 111, mass: "[282]", row: 7, col: 11, category: "unknown" },
  { symbol: "Cn", name: "Copernicium", number: 112, mass: "[285]", row: 7, col: 12, category: "transition-metal" },
  { symbol: "Nh", name: "Nihonium", number: 113, mass: "[286]", row: 7, col: 13, category: "post-transition" },
  { symbol: "Fl", name: "Flerovium", number: 114, mass: "[289]", row: 7, col: 14, category: "post-transition" },
  { symbol: "Mc", name: "Moscovium", number: 115, mass: "[290]", row: 7, col: 15, category: "post-transition" },
  { symbol: "Lv", name: "Livermorium", number: 116, mass: "[293]", row: 7, col: 16, category: "post-transition" },
  { symbol: "Ts", name: "Tennessine", number: 117, mass: "[294]", row: 7, col: 17, category: "halogen" },
  { symbol: "Og", name: "Oganesson", number: 118, mass: "[294]", row: 7, col: 18, category: "noble-gas" },

  // Lanthanides
  { symbol: "Ce", name: "Cerium", number: 58, mass: "140.116", row: 9, col: 4, category: "lanthanide" },
  { symbol: "Pr", name: "Praseodymium", number: 59, mass: "140.908", row: 9, col: 5, category: "lanthanide" },
  { symbol: "Nd", name: "Neodymium", number: 60, mass: "144.243", row: 9, col: 6, category: "lanthanide" },
  { symbol: "Pm", name: "Promethium", number: 61, mass: "[145]", row: 9, col: 7, category: "lanthanide" },
  { symbol: "Sm", name: "Samarium", number: 62, mass: "150.36", row: 9, col: 8, category: "lanthanide" },
  { symbol: "Eu", name: "Europium", number: 63, mass: "151.964", row: 9, col: 9, category: "lanthanide" },
  { symbol: "Gd", name: "Gadolinium", number: 64, mass: "157.25", row: 9, col: 10, category: "lanthanide" },
  { symbol: "Tb", name: "Terbium", number: 65, mass: "158.925", row: 9, col: 11, category: "lanthanide" },
  { symbol: "Dy", name: "Dysprosium", number: 66, mass: "162.500", row: 9, col: 12, category: "lanthanide" },
  { symbol: "Ho", name: "Holmium", number: 67, mass: "164.930", row: 9, col: 13, category: "lanthanide" },
  { symbol: "Er", name: "Erbium", number: 68, mass: "167.259", row: 9, col: 14, category: "lanthanide" },
  { symbol: "Tm", name: "Thulium", number: 69, mass: "168.934", row: 9, col: 15, category: "lanthanide" },
  { symbol: "Yb", name: "Ytterbium", number: 70, mass: "173.045", row: 9, col: 16, category: "lanthanide" },
  { symbol: "Lu", name: "Lutetium", number: 71, mass: "174.967", row: 9, col: 17, category: "lanthanide" },

  // Actinides
  { symbol: "Th", name: "Thorium", number: 90, mass: "232.038", row: 10, col: 4, category: "actinide" },
  { symbol: "Pa", name: "Protactinium", number: 91, mass: "231.036", row: 10, col: 5, category: "actinide" },
  { symbol: "U", name: "Uranium", number: 92, mass: "238.029", row: 10, col: 6, category: "actinide" },
  { symbol: "Np", name: "Neptunium", number: 93, mass: "[237]", row: 10, col: 7, category: "actinide" },
  { symbol: "Pu", name: "Plutonium", number: 94, mass: "[244]", row: 10, col: 8, category: "actinide" },
  { symbol: "Am", name: "Americium", number: 95, mass: "[243]", row: 10, col: 9, category: "actinide" },
  { symbol: "Cm", name: "Curium", number: 96, mass: "[247]", row: 10, col: 10, category: "actinide" },
  { symbol: "Bk", name: "Berkelium", number: 97, mass: "[247]", row: 10, col: 11, category: "actinide" },
  { symbol: "Cf", name: "Californium", number: 98, mass: "[251]", row: 10, col: 12, category: "actinide" },
  { symbol: "Es", name: "Einsteinium", number: 99, mass: "[252]", row: 10, col: 13, category: "actinide" },
  { symbol: "Fm", name: "Fermium", number: 100, mass: "[257]", row: 10, col: 14, category: "actinide" },
  { symbol: "Md", name: "Mendelevium", number: 101, mass: "[258]", row: 10, col: 15, category: "actinide" },
  { symbol: "No", name: "Nobelium", number: 102, mass: "[259]", row: 10, col: 16, category: "actinide" },
  { symbol: "Lr", name: "Lawrencium", number: 103, mass: "[266]", row: 10, col: 17, category: "actinide" }
];

const HIDDEN_ELEMENTS = new Set([
  "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
  "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr"
]);

const VISIBLE_PERIODIC_ELEMENTS = PERIODIC_ELEMENTS.filter(
  element => !HIDDEN_ELEMENTS.has(element.symbol)
);
